// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOm-biTGofThW_DlJVy9_UbFWm6Ise9aA',
    appId: '1:845587109394:web:39656302c337dd32932acb',
    messagingSenderId: '845587109394',
    projectId: 'task-management-apps-ab7cb',
    authDomain: 'task-management-apps-ab7cb.firebaseapp.com',
    storageBucket: 'task-management-apps-ab7cb.appspot.com',
    measurementId: 'G-5DGN24DY9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHiNwtx5v8yk3W413eYbyQrjDDZIxKU5Y',
    appId: '1:845587109394:android:297b5b9be901b4b3932acb',
    messagingSenderId: '845587109394',
    projectId: 'task-management-apps-ab7cb',
    storageBucket: 'task-management-apps-ab7cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz0-hUZkCRlG1Hne5VWrurrYD3ROzxzV4',
    appId: '1:845587109394:ios:363e0cab33728ce8932acb',
    messagingSenderId: '845587109394',
    projectId: 'task-management-apps-ab7cb',
    storageBucket: 'task-management-apps-ab7cb.appspot.com',
    androidClientId: '845587109394-6a46pvhndsmf1elm9njou4v705de638a.apps.googleusercontent.com',
    iosClientId: '845587109394-40fri78kgq2iboen2l9o8ftlfbfs9m5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
